# Generated by Django 6.0.6 on 2026-06-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('specversion', models.CharField(max_length=10)),
                ('event_type', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('node', models.CharField(max_length=255, db_column='node')),
                ('event_time', models.DateTimeField()),
                ('datacontenttype', models.CharField(max_length=100)),
                ('dataschema', models.TextField(blank=True, null=True)),
                ('conforms_to', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(max_length=50)),
                ('subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('wnm', models.JSONField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('tests', models.JSONField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('incident_hash', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-event_time'],
                'managed': False,
            },
        ),
    ]
