# Generated by Django 6.0.6 on 2026-07-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0007_incidentevent_incidentmute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'node_responsibles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeResponsibleMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_column='assigned_at')),
            ],
            options={
                'db_table': 'node_responsible_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
