# Generated by Django 6.0.6 on 2026-07-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0009_remove_alert_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmute',
            name='incident_hash',
            field=models.TextField(db_index=True),
        ),
    ]
