# Generated by Django 5.2.16 on 2026-07-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0010_alter_incidentmute_incident_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentmute',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
