# Generated by Django 5.2.16 on 2026-08-02 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0012_raw_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRetentionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.PositiveIntegerField(blank=True, help_text='Delete alerts older than this many days. Leave empty to keep alerts forever (persistence).', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'alert retention policy',
                'verbose_name_plural': 'alert retention policy',
                'db_table': 'alert_retention_policy',
            },
        ),
    ]
