# Generated by Django 5.2.16 on 2026-08-03 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0013_alertretentionpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertretentionpolicy',
            name='ttl_active',
            field=models.BooleanField(default=False, help_text='Enable the alert TTL. When disabled, alerts are kept forever.'),
        ),
        migrations.AlterField(
            model_name='alertretentionpolicy',
            name='retention_days',
            field=models.PositiveIntegerField(blank=True, help_text='Delete alerts older than this many days. Required when TTL is active.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
