# Generated by Django 5.2.16 on 2026-08-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0016_rename_node_to_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectResponsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'subject_responsibles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectResponsibleMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_column='assigned_at')),
            ],
            options={
                'db_table': 'subject_responsible_mapping',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='NodeResponsible',
        ),
        migrations.DeleteModel(
            name='NodeResponsibleMapping',
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='event_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('email_sent', 'Email Sent'), ('note_added', 'Note Added'), ('note_removed', 'Note Removed'), ('muted', 'Muted'), ('unmuted', 'Unmuted'), ('viewed', 'Viewed'), ('jira_ticket', 'Jira Ticket')], max_length=20),
        ),
    ]
